version: "3.7"
services:
  application:
    image: councellor-enquiry-portal
    build: .
    restart: always
    ports:
      - 9090:9090
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - mysql

    volumes:
      - .m2:/root/.m2

  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      #MYSQL_USER: root
      MYSQL_PASSWORD: Kunal@123
      MYSQL_ROOT_PASSWORD: Kunal@123
networks:
  springapimysql-net:
