version: "3.7"

services:
  application:
    image: Councellor-Enquiry-Portal
    networks:
      - councellor-network
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/Councellor
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      
    ports:
      - 9090:9090
    volumes:
      - councellor-app-data:/data/councellor-app

  mysqldb:
    image: mysql:8.0.33
    networks:
      - councellor-network
   
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Councellor
      
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  councellor-network:

volumes:
  mysql-data:
  councellor-app-data:
