version: "3.8"

services:
  application:
    image: Councellor-Enquiry-Portal
    ports:
      - 9090:9090
    networks:
      - councellor-network
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - /data/councellor-app

  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Councellor
    networks:
      - councellor-network
    volumes:
      - /data/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  councellor-network:
