version: "3"
services:
 application:
  image: Councellor-Enquiry-Portal
  ports:
  - 9090:9090
  networks:
  - councellor-network
  depends_on:
  - mysqldb
  volumes:
  - /data/councellor-app
  
  
 mysqldb:
  image: mysql:8.0
  networks:
  - councellor-network
  ports:
     - "3306:3306"
  
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=Councellor
  
  volumes:
    - /data/mysql

networks:
 councellor-network:

