spring:
  application:
    name: Councellor-Enquiry-Portal
  datasource:
    url:  jdbc:mysql://mysqldb:3306/Councellor?useSSL=false&allowPublicKeyRetrieval=true
    password: root
    username: root    
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port:  9090